spring:
  application:
    name: g-40-1-shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB+USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: Sf2/MZFPvvbKmQufF/XJ23MOpIV6cJysnEaQ7veRATU=
  refresh: N8VjRs2JtsJJpyB887zFbD4qye9loQxKx5iZ418V1Xs=

messages:
  hello: Hello from Digital Ocean!