spring:
  application:
    name: g-40-1-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/g_40_1_shop
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true